image: python:3.9

stages:
  - build

variables:
  AWS_CLI_VERSION: "2.11.9"
  S3_BUCKET_NAME: "proyectodiplo"  

before_script:
  # Actualiza pip a la última versión
  - python -m pip install --upgrade pip

# Este job se realiza solo para merge requests a main
main_file_saving:
  stage: main_file_saving
  only:
    # Aca aclaro que este job solo se ejecuta con merge a dev
    - main
  script:
    # Install the AWS CLI
    - pip install awscli
    - echo "AWS CLI installed"
    # Verify the installed AWS CLI version
    - aws --version == $AWS_CLI_VERSION
    - echo "La versión instalada del CLI de AWS es $AWS_CLI_VERSION"
    # Configura las credenciales de AWS (puedes usar variables de entorno para mayor seguridad)
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - echo "AWS user access granted"
    # Copia el archivo al bucket de S3 y sobrescribe si ya existe
    - aws s3 cp $FILE_TO_UPLOAD s3://$S3_BUCKET_NAME/ --acl public-read
    - echo "S3 bucket updated"
    # Guardado de un archivo a mi bucket
    - echo "Pull request is ready for aproval"
  tags:
  # este tag corresponde al runner que correra este job
    - main-docker-tag


